name = "curso-backend"
main = "src/index.ts"
compatibility_date = "2024-11-12"

compatibility_flags = ["nodejs_compat"]  # ✅ Adicione esta linha

[vars]
ALLOWED_ORIGIN = "http://localhost:5173"
# Em produção: `wrangler secret put DATABASE_URL`
