name = "curso-backend"
main = "src/index.ts"   # (ou src/index.ts, se for o seu)
compatibility_date = "2024-11-12"

[vars]
ALLOWED_ORIGIN = "http://localhost:5173"
# Em produção: `wrangler secret put DATABASE_URL`
